export const LearningJourneyEvents = {
  SESSION_STARTED: 'SESSION_STARTED',
  STAGE_UNLOCKED: 'STAGE_UNLOCKED',
  STAGE_TRANSITIONED: 'STAGE_TRANSITIONED',
  DISCOVERY_RECORDED: 'DISCOVERY_RECORDED',
  EVIDENCE_CONNECTED: 'EVIDENCE_CONNECTED',
  SYNTHESIS_SUBMITTED: 'SYNTHESIS_SUBMITTED',
  FACILITATOR_GUIDANCE_RELEASED: 'FACILITATOR_GUIDANCE_RELEASED',
  REFLECTION_PROMPT_TRIGGERED: 'REFLECTION_PROMPT_TRIGGERED'
};

export const DiscoveryCategories = {
  ARTIFACT: 'artifact',
  OBSERVATION: 'observation',
  INTERVIEW: 'interview',
  LAB_RESULT: 'lab_result',
  TIMELINE_EVENT: 'timeline_event'
};
